### ISSUE TITLE
Feature: Right-click on folder in places shows the content of the folder

### ISSUE THREAD

**Issue by ghost** [Schneegans/Gnome-Pie#1]
Something similar to the application-menu, where clicking on a category opens the items in the category, but applied to the filesystem.

**Comment by Schneegans** [comment]
As Gnome-Pie is now in _low-maintanance-mode_, I won't have the time to work on this. If you're using GNOME Shell and if you are still interested in this project, you could try out [Fly-Pie](https://github.com/Schneegans/Fly-Pie) which is a successor project of Gnome-Pie.
