### ISSUE TITLE
Feature request : Kill app from "Group: Windows List" pie.

### ISSUE THREAD

**Issue by WhippetsAintDogs** [Schneegans/Gnome-Pie#131]
It'll be great if we could kill process from the Group: Windows List pie. (With the left or middle click) :)

**Comment by Schneegans** [comment]
As Gnome-Pie is now in _low-maintanance-mode_, I won't have the time to implement this. If you're using GNOME Shell and if you are still interested in this project, you could try out [Fly-Pie](https://github.com/Schneegans/Fly-Pie) which is a successor project of Gnome-Pie. Fly-Pie does not yet support the behavior you are looking for, but we could definitely discuss this idea over there!
