### ISSUE TITLE
Replace right click

### ISSUE THREAD

**Issue by ghost** [Schneegans/Gnome-Pie#15]
what if it could replace right click anywhere. 
So it reads the options that would appear in the classic list popup, and instead of that popup list which is used since forever, this opens with the same choices.

**Comment by Schneegans** [comment]
I have actually released [Fly-Pie](https://github.com/Schneegans/Fly-Pie) about a year ago. It supports opening menus via a D-Bus protocol, so each application (e.g. Firefox) could implement support for Fly-Pie. So it should be possible to create an extension for Firefox which opens a Fly-Pie menu for the context menu!

As Gnome-Pie is now in _low-maintanance-mode_, I won't have the time to implement something like this here. But if you're using GNOME Shell and if you are still interested in this project, you could try out [Fly-Pie](https://github.com/Schneegans/Fly-Pie).
