### ISSUE TITLE
Adding applications (desktop files) becomes difficult when there're many applications

### ISSUE THREAD

**Issue by KSXGitHub** [Schneegans/Gnome-Pie#154]
I cannot take a screenshot while showing the drop-down menu but I take screenshot of the dialog

![image](https://user-images.githubusercontent.com/11488886/29333344-a27b95b8-822d-11e7-9eda-b31b19f77778.png)

Now, look at the "Command to execute" box, it has an arrow button on the right to display a drop-down list of installed apps (`.desktop` files). When there are many apps installed, most apps hidden and very hard to find (user can still find it with enough patient).

![image](https://user-images.githubusercontent.com/11488886/29333988-0744677a-8230-11e7-8016-bd523aee10fe.png)

I suggest replace drop-down list with a dialog that contains a list of apps and a text-box to filter them

**Comment by Simmesimme** [comment]
While this is a nice idea, I won't have the time to implement this right now. So if anybody want's to do it.... just feel free :)

**Comment by GuenMat** [comment]
I have an issue with this, I am using ubuntu 18.10 and just discovered gnome pie.
But I can not access my application list as scrolling down is not allowed.

I know a workaround is to set the command to execute manually, but it is quite a hassle.
How do people use this fonctionnality ? Do I have something to activate ? A settings to change ?
Any help will be greatly appreciated. Thank you for your work.

![Capture d’écran du 2019-04-06 13-53-42](https://user-images.githubusercontent.com/35100793/55669099-b3a61480-5873-11e9-81b6-6859bd16a9a8.png)

**Comment by GuenMat** [comment]
Well I just discovered that I should not open the drop down menu to pick an application, but simply keep the cursor on the drop down menu without opening it, and use arrows to get the app I want.

**Comment by gabdub** [comment]
I'm running Ubuntu Mate 18.10 here and a couple of arrows are shown at the top and at the bottom of the list that allows scrolling. It seems like yours are outside of the view. Also the scroll-wheel works for me. It could be an issue with your theme.

**Comment by GuenMat** [comment]
You are totally right. I use Yaru-Dark. 
If I switch to the default theme, the scroll-wheel starts working again :)

I knew there must be something wrong with my config, but I did not think about the theme.
Thank you !

**Comment by Schneegans** [comment]
I guess that this can be closed. Btw, if you are still interested in this project, you could try out [Fly-Pie](https://github.com/Schneegans/Fly-Pie) which is a successor project of Gnome-Pie. Fly-Pie has a better application-select-dialog :smile: .
