### ISSUE TITLE
Pin apps in application switcher

### ISSUE THREAD

**Issue by jerome-caucat** [Schneegans/Gnome-Pie#162]
Hello,

First of all, thank you for your hard work, this is awesome!

I would like to be able to pin applications in the application switcher (or in a new type of item) in order to have the following behavior:
- Show the launched and pinned apps in the list
- On click on a pinned app: if the app is not launched: launch the app
- On click a pinned app: if the app is launched: switch to the app
- Have an option to pin/unpin apps in the list

What do you think?
In the meantime I guess I will write custom launchers, probably using wmctrl, but it will not be optimal.

Cheers,
Jerome.

**Comment by Simmesimme** [comment]
While this is a nice idea, I won't have the time to implement this right now. So if anybody want's to do it.... just feel free :)

**Comment by Schneegans** [comment]
As Gnome-Pie is now in _low-maintanance-mode_, I won't have the time to implement this. If you're using GNOME Shell and if you are still interested in this project, you could try out [Fly-Pie](https://github.com/Schneegans/Fly-Pie) which is a successor project of Gnome-Pie. Fly-Pie does not yet support the behavior you're looking for, but we can discuss such features over there!
