### ISSUE TITLE
Confused about the main menu feature

### ISSUE THREAD

**Issue by Hebgbs** [Schneegans/Gnome-Pie#183]
...What does it do exactly? I thought it would arrange my applications — all applications I have installed — in a circle, categorized like the menus I would use for program access traditionally.

I am using the MATE desktop. Is there some optional deps for GNOME Shell I need to include so GNOME Pie can do its thing correctly rather than showing me absolutely nothing?

**Comment by Hebgbs** [comment]
Found the problem:
`[WARNING] Failed to look up menu_file for "applications.menu"`

But now what's the solution?

**Comment by Hebgbs** [comment]
Figured out a good temp fix, at the very least. It's not the best way of doing things but this helped:
`sudo ln -s /etc/xdg/menus/gnome-applications.menu /etc/xdg/menus/applications.menu`

Not sure why Manjaro does that. But now I wonder, what's the _proper_ way to fix it? Because using a symbolic link feels like cheating...

**Comment by Schneegans** [comment]
I found some information here: https://developer.gnome.org/menu-spec/. It seems that there could be various menu definitions, one for each desktop environment. Gnome-Pie could check whether `applications.menu` exists and if not search for an alternative.

But in the meantime, your workaround seems reasonable...

**Comment by Hebgbs** [comment]
Hey Simon, just wanted to chime in and say that `gnome-menus` from extra is required to be installed for use on Arch. That's what renders the option of `gnome-applications.menu` to be available in `/etc/xdg/menus`.
