### ISSUE TITLE
Click/touch on pie's center go back one level

### ISSUE THREAD

**Issue by mfauvain** [Schneegans/Gnome-Pie#185]
Hi, great app, using it quite a lot. Recently on a surface go, works perfect but would like to see a new feature : touch (or click) on pie's center would go back to previous/parent pie (in case of linked pies) or close the current pie (as it does today) if the current pie has no 'parent'.
Clicking on the outside of the pie would simply close it as it does today.

**Comment by Schneegans** [comment]
Architecture-wise this would be hard to implement as there is no real concept of "linked pies". You can just create actions which open new pies; but these new pies have no idea that they have been opened by another pie.

However, there's already an alternative approach possibility: You may create a "Navigate Back" item in the child pie and set this to be the "Quick Action" of the child. This way, you will navigate back when clicking the center!

**Comment by mfauvain** [comment]
Thx for quick answer. I didn't know the use of quick action actually.. will try that.

**Comment by Schneegans** [comment]
I guess this can be closed.
