### ISSUE TITLE
Load pie on hover particular area on screen

### ISSUE THREAD

**Issue by KizunaH** [Schneegans/Gnome-Pie#187]
Is it possible to configure for load pie when bring cursor to certain area on screen? Eg: appear gnome dock when bring cursor to left side. I noticed https://github.com/thjaeger/easystroke however not as expected.

**Comment by Schneegans** [comment]
If you are on GNOME Shell, you could try https://extensions.gnome.org/extension/1037/customcorner/

Does this work for you?

**Comment by KizunaH** [comment]
How to configure it to load pie? however can't you implement such feature on gnome-pie?

I tested with default options: show overview, show apps grid but it seems not compatible with 20.04.01 because it hard to open eg: apps grid by hover, often flash screen only.

**Comment by Schneegans** [comment]
There is also https://extensions.gnome.org/extension/1362/custom-hot-corners/. Maybe this works better? Just use the command `gnome-pie -o <ID of your pie>` to open your desired menu.

https://schneegans.github.io/gnome-pie.html#advanced-usage

**Comment by KizunaH** [comment]
It works as expected. you can close this issue if doesn't has intention to implement it
