### ISSUE TITLE
Make session control configurable

### ISSUE THREAD

**Issue by Hebgbs** [Schneegans/Gnome-Pie#188]
Sounds like  dumb thing to ask but the session control group doesn't work _as expected_ across all desktop shells, and being able to sefine what each of the buttons do would be pretty dope. I do know people can just make their own session control pie but it would save people _so much effort_ for theming and tinkering if the option to define what each button does was made available.

**Comment by Schneegans** [comment]
As Gnome-Pie is now in _low-maintanance-mode_, I won't have the time to implement this. If you're using GNOME Shell and if you are still interested in this project, you could try out [Fly-Pie](https://github.com/Schneegans/Fly-Pie) which is a successor project of Gnome-Pie. It also has a session-control menu, but - as said before - it's limited to GNOME Shell...
