### ISSUE TITLE
can not install under fedora-34 with compile error [resolved]

### ISSUE THREAD

**Issue by jerome-diver** [Schneegans/Gnome-Pie#191]
I'm trying to install gnome-pie (now on Fedora-34, but works under Archlinux) and did install all dependancies (even if there name are not same than debian packages ones).
At compilation time i get an error:
/opt/Gnome-Pie/build/src/utilities/archiveWriter.c:28:10: fatal error: archive.h: file does not exist

notice that i have also this (i think in relation):
ARCHIVE_LIBRARIES = ARCHIVE_LIB-NOTFOUND
as env variable before to install

Do you have a rpm package able to install on Fedora-34 ?
I want to use Gnome-pie and not fly-pie, because i do not use Gnome, but Awesome. I like your pie menu and used it under Archlinux with Awesome desktop. I want the same config on my office PC (who is under Fedora-34).
Thank you for your help or any information to fix the problem.

**Comment by jerome-diver** [comment]
I failed to get all dependencies... and most specificaly libarchive-devel that i see from your web site and doesn't check and indicate from source code at compile time.
So you should add check for libarchive-devel presence at compile time.

**Comment by Schneegans** [comment]
I think some packaged it for Fedora 34 already: https://fedora.pkgs.org/34/rpm-sphere-x86_64/gnome-pie-0.7.2-1.x86_64.rpm.html
But I am glad you figured this out!
