### ISSUE TITLE
see window around the Gnome-Pie graph

### ISSUE THREAD

**Issue by jerome-diver** [Schneegans/Gnome-Pie#192]
On archlinux i didn't see this window container around the gnome-pie graph.
On Fedora-34, i do install it from github clone then compile, and i see the window container.
What i did wrong and how to fix this please ?

**Comment by Schneegans** [comment]
This behavior strongly depends on the window manager and there seems to be no real ubiquitous solution. Which window manager are you using? Gnome-Pie actually requests a not-decorated window:
https://github.com/Schneegans/Gnome-Pie/blob/02e26da4ee56c3874df20dc49336ede07acce107/src/renderers/pieWindow.vala#L128
But this is ignored by some. There is also the type hint, which makes some window managers remove decorations:
https://github.com/Schneegans/Gnome-Pie/blob/02e26da4ee56c3874df20dc49336ede07acce107/src/renderers/pieWindow.vala#L127
You could try another type hint there. Here's a list: https://valadoc.org/gdk-3.0/Gdk.WindowTypeHint.html
For example, `this.set_type_hint(Gdk.WindowTypeHint.SPLASHSCREEN);` _could_ work.

**Comment by jerome-diver** [comment]
I'm using Awesome tiling Window Manager.
When i use it under Archlinux with Gnome-Pie; these window container doesn't appear, and under Fedora-34 with awesome, it does appear.
So i conclude that it should be possible to do the same (no window container to appear) on the same Window manager (Awesome) but with different operating system... so the question is not "Can i do it", but much more: "How to do it" ?
I thing that if i can be able to understand "WHY" this does append, then i should be able also to find the solution...

**Comment by Schneegans** [comment]
Did you compile it on Arch from source as well? Maybe the package maintainers modified this part?

**Comment by jerome-diver** [comment]
No, from AUR repo named "gnome-pie-git"

**Comment by Schneegans** [comment]
Maybe they took the `develop` branch of Gnome-Pie. There it's set to `DIALOG`.
