### ISSUE TITLE
Windows in Window List crash on Linux Mint 20.2

### ISSUE THREAD

**Issue by Glint-Eye** [Schneegans/Gnome-Pie#194]
Ever since i updated to Linux Mint (Cinnamon) 20.2 gnome-pie crashes from the Window List in the panel. The app window is still open, but there is no more entry in the window list. Also, when I access a filepath to a folder through a pie, the same behaviour occurs. Window in Window List crashes, App Window still accessible through Alt+Tab

**Comment by Schneegans** [comment]
Hi there! Thanks for the report - even if I am unsure whether I understood the problem correctly :)

Anyways, could you try to execute this command in a terminal

```
killall gnome-pie && gnome-pie
```

and then open your menus and post the output here?

**Comment by Glint-Eye** [comment]
Hey. Thx for the quick answer!

Yeah its hard to describe. I've made a screenshot to show what I mean. Those are 3 windows in the window list (thats how the applet for open windows is called in cinnamon). I've used the command you've posted, and by that started gnome-pie in terminal, but I got completley no ouput "Started happily..." after that nothing, also not after this behaviour happened. I've opened "Downloads" and "Documents" through the default Ctrl+Alt+B Pie. The "Documents" folder had the behaviour. It becomes red and once i hover over the red "Documents" icon, it disappears from the window list, but the window itself stays open, its just not accessible through the window list anymore. This happens with all kind filepaths i can open with gnome pie. but it doesnt happen 100% of the time. the gnome settings window in the window list also sometimes crashes, turns red and disappears like "Downloads".

Sorry for the rather colloquial description, i'm not the most tech savvy person :P

![Screenshot from 2021-07-14 12-36-04](https://user-images.githubusercontent.com/87322712/125608737-e794cf9d-5f22-4e7d-9500-2924e8f89e0b.png)

**Comment by Schneegans** [comment]
Well, I have no idea what could be going on here. Do they re-appear if you restart Cinnamon (Alt+F2, enter "r", then enter)? You could also try to inspect the logs of Cinnamon. I think there's a tool called _LookingGlass_. Should be accessible through the panel (Right Click - Look for Errors - Looking Glass; or something similar). Linux Mint also has some build-in log viewer, I think. It should be somewhere in the application menu...

**Comment by Glint-Eye** [comment]
okay. it seems to be issue on cinnamons side and probably has nothing to do with gnome-pie. it's just the first app where i experienced this behaviour. here's an issue thread for cinnamon, where people describe the same behaviour with libreoffice writer instances. 

https://github.com/linuxmint/cinnamon/issues/10202

and... i just got a cinnamon update in the update manager. the behaviour changed, although not completely fixed. at least now the entries don't disappear from the window list anymore.

thanks again for your quick replies. i appreciate that!

Btw, will there, by any chance, be a cinnamon compatible version of fly-pie? i really love gnome-pie and so far it's the best launcher application for me. so i would love to be able to give fly-pie a try to.   

Cheers.

**Comment by Schneegans** [comment]
As Cinnamon got forked around eight years ago, I am pretty sure that it's not possible to support both GNOME Shell and Cinnamon from the same code base. If someone wants to fork Fly-Pie for Cinnamon, that would be great, but I won't have the time to do this... I guess it would be a lot of work (if even possible at all, Fly-Pie is kind of deeply integrated into GNOME Shell).
