### ISSUE TITLE
Feature: fullscreen layers in themes

### ISSUE THREAD

**Issue by rtraverso86** [Schneegans/Gnome-Pie#20]
Hi again,

I was trying to define a new theme and I came up with this idea.  What about a new kind of fullscreen layers in the themes? I would like to define one with a fullscreen black background (or something like that) in order to make sure nothing visually bothers you while selecting a pie, but the closest thing is relying on center layer scaled big enough to fill the whole screen. This is not a solution obviously, since the scaling factor chosen by the user in the config window could compromise the final result.

**Comment by Schneegans** [comment]
As Gnome-Pie is now in _low-maintanance-mode_, I won't have the time to work on this. If you're using GNOME Shell and if you are still interested in this project, you could try out [Fly-Pie](https://github.com/Schneegans/Fly-Pie) which is a successor project of Gnome-Pie. Fly-Pie supports tinting the entire screen!
