### ISSUE TITLE
! Good Look & Feel Solutions ...

### ISSUE THREAD

**Issue by sudoquai** [Schneegans/Gnome-Pie#40]
- Left Mouse Button with delay is best in my opinion for selecting (check if user is dragging a window or something else that could activate gnome-pie or just left clicking on desktop)
- The center (black circle) of the actual pie could be used to show a zoomed picture of the actual menu entry)
- Rotating Pie which scrolls using the middle mouse wheel (cursor keys) while resting with mouse over a menu entry (keeps the eye on one place, maybe the center where the zoomed picture is shown like described above).
- Vanishing menu entries (combined with rotating pie):
  Menu entries of the rotating pie could vanish at some point of the circle, while rotating it. The visible menu entries while rotating could be reduced to maximum 10-15.
- Dynamic pie menus: Drag & Drop to a virtual clipboard (maybe an other pie menu) to reorganize menu entries with dragging back to his new place, Drag & Drop to a virtual trashcan to delete menu entries.
- Better cancel and select behaviour for pies:
  left clicking on a other place than a menu entry should cancel pie menu (like pressing ESC). The behaviour at the moment is: Left clicking defines the center of the new pie menu if it is a node/submenu and selects the actually activated entry. In my opinion the user should define with the first click where all following pie menus should be opened and is responsible for invisible entries (out of screen).
  This could be solved as well with a rotating pie menu (middle mouse scroll wheel while resting with the mouse cursor on the same place with leftclicking to select) as mentioned above.
- Search box to perform a quick textual search for a menu entry. (like gnomedo)
- Intelligent opening of submenus:
  Resting 2-3 seconds over a submenu entry opens the submenu pie, while the top menu is staying open and opens the new submenu next to the submenu entry (touching it).
- Indication of already opened applications.
  Already opened applications could be indicated by a glowing menu entry (or an other special effect). Selection of the glowing menu entry selects the minimized or hidden application instead of opening a fresh instance. Gnomedo has this very usefull feature.
- History making unused icons 50% transparent, 0% transparency for often used menu entries (more than 10-20 should not be possible)

Thats just some suggestions to improve pie menu :) A very good product is worth improving it. I've seen simme you've been inspired by a WOW addon - some of these features could be found in similar addons for WOW as well - they were very usefull for my Pala and Shadowpriest :D

Thx

**Comment by Schneegans** [comment]
These ideas have been requested ten years ago... I think some of them got actually implemented over the years. But as Gnome-Pie is now in _low-maintanance-mode_, I won't have the time to work on this any more. If you're using GNOME Shell and if you are still interested in this project, you could try out [Fly-Pie](https://github.com/Schneegans/Fly-Pie) which is a successor project of Gnome-Pie.
