### ISSUE TITLE
Scripting 

### ISSUE THREAD

**Issue by Aluminium95** [Schneegans/Gnome-Pie#52]
Hello,
It would be nice if there were some ways to use scripting language (like lua/scheme/js) to create dynamic items in pies.
Or to dynamicly change pies.

For example, in the music controler, an item which displays the current playing song (only refreshed at the loading of a pie, for ressource saving). And if there is no playing song, the item is not displayed. 

I know there are some ways to use lua scripts into vala code, calling vala functions into lua code, and lua functions into vala code. (http://valadoc.org/#!api=lua/Lua)

Thanks for reading, and sorry for my very bad english

**Comment by michael-at** [comment]
Hello together!

As a first (and hopefully easy start) maybe an command line option could be implemented to force a manual reload of an users pies.conf file.

After playing a little around in the command line, i managed to write a (bash)script that updates the pies.conf whenever a sub-folder is created/deleted/modified in a monitored folder thus providing me with a pie that (dynamically) contains all the sub-folders of the monitored folder.

So far i have to close and reopen gnome-pie every time i want the modified pies.conf to be reloaded.

Therefore a command like gnome-pie --reload-config (or --reload-pies) would be much appreciated and an fast start to enable further scripting.

Anyway thanks for this beautiful applications and
Best Regards
Michael

**Comment by Simmesimme** [comment]
That should be straight-forward to implement. We could even go one step further and monitor the config file. So if it is changed from anywhere, it is automatically reloaded.

**Comment by Schneegans** [comment]
As Gnome-Pie is now in _low-maintanance-mode_, I won't have the time to implement this. If you're using GNOME Shell and if you are still interested in this project, you could try out [Fly-Pie](https://github.com/Schneegans/Fly-Pie) which is a successor project of Gnome-Pie. Fly-Pie supports the creation of dynamic menus quite well!
