### ISSUE TITLE
More a request than an issue. Mouse mapping depend upon mouse/trackpad

### ISSUE THREAD

**Issue by tr33m4n** [Schneegans/Gnome-Pie#56]
Hello there,

Some wonderful work going on here. I'm considering releasing a distro using this as the main menu system, however there are some issues I have. The main one at present is, what would the best way to go about changing the shortcuts depending on whether a laptop is using a trackpad or a mouse?

Middle click for a menu is great when a mouse is plugged in, but another shortcut would need to be defined if using a trackpad due to many of them not supporting a middle click.

Any idea how to go about this?
Cheers
Dan

**Comment by i-need-to-tell-you-something** [comment]
I believe there is also an configuration option in some/most Linux trackpad drivers to have middle click emulated when both trackpad buttons are pressed simultaneously. And if you find a driver that covers 95% of your users, then the last 5% can just be instructed to change the hotkey to something they like.

**Comment by Schneegans** [comment]
As Gnome-Pie is now in _low-maintanance-mode_, I won't have the time to work on this. If you're using GNOME Shell and if you are still interested in this project, you could try out [Fly-Pie](https://github.com/Schneegans/Fly-Pie) which is a successor project of Gnome-Pie. Fly-Pie is actually made to work well with touch-pads!
